<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder();
$currencyCode = $_order ? $_order->getOrderCurrencyCode() : 'GBP';
 ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <div class="hse-section" style="padding-left:10px; padding-right:10px">
    <!--[if !((mso)|(IE))]><!-- -->
        <div class="hse-column-container" style="min-width:280px; width:100%; Margin-left:auto; Margin-right:auto; border-collapse:collapse; border-spacing:0; background-color:#ffffff; max-width: 500px !important;" bgcolor="#ffffff">
        <!--<![endif]-->
        <!--[if (mso)|(IE)]>
			<div class="hse-column-container" style="min-width:280px;max-width:600px;width:100%;Margin-left:auto;Margin-right:auto;border-collapse:collapse;border-spacing:0;">
			<table align="center" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;width:600px;" cellpadding="0" cellspacing="0" role="presentation" width="600" bgcolor="#ffffff">
			<tr style="background-color:#ffffff;">
			<![endif]-->
	
			<!--[if (mso)|(IE)]>
			<td valign="top" style="width:600px;">
			<![endif]-->
			<!--[if gte mso 9]>
			<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;width:600px">
			<![endif]-->
            <div class="hse-column hse-size-12" style="width: 500px !important; max-width: 500px !important">
                <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-spacing:0 !important; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt">
                        <?php foreach ($_items as $_item): ?>
                            <?php
                                if ($_item->getParentItem()) {
                                    continue;
                                }
                            ?>
                            <tbody>
                                <?= $block->getItemHtml($_item) ?>
                            </tbody>
                        <?php endforeach; ?>
                    </table>
            </div>
            <!--[if gte mso 9]></table><![endif]-->
			<!--[if (mso)|(IE)]></td><![endif]-->
			<!--[if (mso)|(IE)]></tr></table><![endif]-->
        </div>
    </div>
    <div class="hse-section" style="padding-left:10px; padding-right:10px">
    <!--[if !((mso)|(IE))]><!-- -->
        <div class="hse-column-container" style="min-width:280px; width:100%; Margin-left:auto; Margin-right:auto; border-collapse:collapse; border-spacing:0; background-color:#ffffff;padding-top: 0px;max-width: 500px !important;" >
    <!--<![endif]-->
    <!--[if (mso)|(IE)]>
			<div class="hse-column-container" style="min-width:280px;max-width:600px;width:100%;Margin-left:auto;Margin-right:auto;border-collapse:collapse;border-spacing:0;">
			<table align="center" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;width:600px;" cellpadding="0" cellspacing="0" role="presentation" width="600" bgcolor="#ffffff">
			<tr style="background-color:#ffffff;">
			<![endif]-->
	
			<!--[if (mso)|(IE)]>
			<td valign="top" style="width:600px;">
			<![endif]-->
			<!--[if gte mso 9]>
			<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;width:600px">
			<![endif]-->
            <div class="hse-column hse-size-12">
                <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-spacing:0 !important; border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; background-color: #fff">
					<tbody>
                        <tr>
							<td height="12" align="left" valign="top" style="border-collapse:collapse; mso-line-height-rule:exactly; font-size:px;display:none">&nbsp;</td>
                            <td height="12" align="left" valign="top" style="border-collapse:collapse; mso-line-height-rule:exactly; font-size:px;display:none">&nbsp;</td>
						</tr>
                        <?= $block->getChildHtml('order_totals') ?>
                        <tr>
							<td height="12" align="left" valign="top" style="border-collapse:collapse; mso-line-height-rule:exactly; font-size:px;">&nbsp;</td>
                            <td height="12" align="left" valign="top" style="border-collapse:collapse; mso-line-height-rule:exactly; font-size:px;">&nbsp;</td>
						</tr>
                    </tbody>
                </table>
            </div>
            <!--[if gte mso 9]></table><![endif]-->
			<!--[if (mso)|(IE)]></td><![endif]-->
			<!--[if (mso)|(IE)]></tr></table><![endif]-->
        </div>
    </div>                
<?php endif; ?>
